### PR TITLE
Upgrade to react 18

### PR DESCRIPTION
**Pull request by TrySound**
Ref https://react.dev/blog/2022/03/29/react-v18 https://react.dev/blog/2022/03/08/react-18-upgrade-guide

- bumped all deps to use react 18
- storybook still somehow enforces react 17 (but not react-dom) so forces with overrides until bump of storybook
- both storybook and remix still use legacy api so concurrent features are not yet enabled. Will do in separate PRs
- fixed weird react-hot-toast error which expose function as renderable type
- fixed a few untyped useCallback which failed with new react types
- sdk size became a little bigger

## Code Review

- [ ] hi @kof, I need you to do
  - conceptual review (architecture, feature-correctness)
  - test it on preview
- [ ] hi @istarkov, I need you to do
  - detailed review (read every line)

## Before requesting a review

- [ ] made a self-review
- [ ] added inline comments where things may be not obvious (the "why", not "what")

## Before merging

- [ ] tested locally and on preview environment (preview dev login: 5de6)
- [ ] updated [test cases](https://github.com/webstudio-is/webstudio-builder/blob/main/apps/builder/docs/test-cases.md) document
- [ ] added tests
- [ ] if any new env variables are added, added them to `.env.example` and the `builder/env-check.js` if mandatory

### CODE REVIEW

**Review by istarkov — APPROVED** [review]
!!!!

**Comment by istarkov** [comment]
Something with local development, canvas loaded like 1ce per 10 reloads. Investigating

**Comment by kof** [comment]
even before switching I had frequently the case that builder loaded but canvas was empty and only after another reload it loaded properly, I am sure we have some problem with ready state of the canvas

**Review by kof — APPROVED** [review]

**Comment by TrySound** [comment]
Merged with sync mode. So all works like in react 17 for now

**Pull request merged**
