### PR TITLE
Change section title color

### LINKED ISSUE #1614: Change color of closed section titles.
Small adjustment. The section titles when closed currently use color token: "foreground.subtle" for the text and icons but this makes them look disabled or something. Let's change them to "foreground.main".

The design is updated.
Screenshot 2023-05-10 at 10 42 23 AM

### PR DESCRIPTION
**Pull request by rpominov**
## Description

Closes #1614

## Code Review

- [ ] hi @TrySound, I need you to do
  - conceptual review (architecture, feature-correctness)
- [ ] hi @taylornowotny, I need you to do
  - test it on preview

## Before requesting a review

- [ ] made a self-review
- [ ] added inline comments where things may be not obvious (the "why", not "what")

## Before merging

- [ ] tested locally and on preview environment (preview dev login: 5de6)
- [ ] updated [test cases](https://github.com/webstudio-is/webstudio-builder/blob/main/apps/builder/docs/test-cases.md) document
- [ ] added tests
- [ ] if any new env variables are added, added them to `.env.example` and the `builder/env-check.js` if mandatory

### CODE REVIEW

**Review by TrySound — APPROVED** [review]

**Comment by TrySound** [comment]
Do we really need cursor: pointer here? Looks very inconsistent with the rest of UI. Maybe show some visual feedback like show icon on hover?

**Comment by rpominov** [comment]
> Do we really need cursor: pointer here?

I used pointer because it is specified in Figma. And now cursor is the only indicator of hover (before this PR color was different)

Screenshot 2023-05-15 at 09 46 49

@taylornowotny We need you to have a look

**Comment by taylornowotny** [comment]
Yea the pointer is meant to show that the section title is interactive. The gray color for a closed section made it look disabled and that wasn't good. Showing icon buttons on hover isn't an option becuase those button need to be available even when the section is closed.

Do you think the pointer is an issue, @rpominov ?

I am open to other suggestions of hover effects.

**Comment by taylornowotny** [comment]
Just tested. The pointer does stand out as being inconsistent like @TrySound says.

Do we need a hover at all? It might be best with default cursor and no hovers

**Pull request merged**
