### PR TITLE
Upgrade to remix 1.16 and fix build

### PR DESCRIPTION
**Pull request by istarkov**
## Description

1. Vercel sets own package for @remix-run/dev https://github.com/vercel/vercel/pull/9784
2. Vercel uses vanilla extract for all `*.css.ts` files executing them during the build that cause our Prisma to fail

TODO:
- [ ] - remove VERCEL_CLI_VERSION before merge at saas and here
- [x] - check some issues with update - many duplicates
- [ ] - size limit increased on 45kb without any reason

## Code Review

- [ ] hi @kof, I need you to do
  - conceptual review (architecture, feature-correctness)
  - detailed review (read every line)
  - test it on preview

## Before requesting a review

- [ ] made a self-review
- [ ] added inline comments where things may be not obvious (the "why", not "what")

## Before merging

- [ ] tested locally and on preview environment (preview dev login: 5de6)
- [ ] updated [test cases](https://github.com/webstudio-is/webstudio-builder/blob/main/apps/builder/docs/test-cases.md) document
- [ ] added tests
- [ ] if any new env variables are added, added them to `.env.example` and the `builder/env-check.js` if mandatory

### CODE REVIEW

**Comment by TrySound** [comment]
Need to revert lockfile and run `pnpm install` again to avoid unnecessary upgrades.

**Comment by TrySound** [comment]
Looks like the issue is tree shaking stopped working. I see other components in included into function.

**Comment by TrySound** [comment]
I also see one props object to be included in bundle

**Comment by TrySound** [comment]
Actually, no. Happens in main too. These components are always included
var Op = { Image: Rs, Link: Mp, RichTextLink: Lp, LinkBlock: Np, Form: Ms };

**Comment by TrySound** [comment]
I guess they switched polyfilling library and it started to bloat our bundle.

**Comment by kof** [comment]
this can be closed I assume

**Pull request closed without merging**
